name: Contracts

on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  pull_request:
    branches:
  workflow_dispatch:

env:
  RUST_LOG: info,libp2p=off

jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Install Nix
        uses: cachix/install-nix-action@v23

      - uses: cachix/cachix-action@v12
        # If PR is from a non-collaborator (e. g. dependabot) the secrets are missing and the login to cachix fails.
        continue-on-error: true
        with:
          name: espresso-systems-private
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community

      - uses: actions/checkout@v4
        name: Checkout Repository
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          prefix-key: v1-rust

      - name: Format check
        run: nix develop --accept-flake-config -c pre-commit run forge-fmt --all-files

      - name: Solhint solidity linter
        run: nix develop --accept-flake-config -c pre-commit run solhint --all-files

      - name: Build contracts
        run: nix develop --accept-flake-config -c forge build --deny-warnings

      - name: Check if bindings up to date
        run: nix develop --accept-flake-config -c pre-commit run contract-bindings --all-files

      - name: Run tests
        run: nix develop --accept-flake-config -c forge test -vvv
